
plugins {
    id 'java'
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.12'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.14.0'
}

application {
    mainClass = 'ricksy.business.RicksyBusiness'
}


jar {
    // desempaqueta todos los JARs de dependencias e incluye sus clases dentro del JAR generado
    // Asi se incluye la clase org.apache.commons.lang3.BooleanUtils de CreditCard
    from configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes( "Manifest-Version": "1.0",
                    "Created-By": "Gradle",
                    "Main-Class": "ricksy.business.RicksyBusiness",
                    "Implementation-Title": "Gradle",
                    "Implementation-Version": archiveVersion )
    }
}


