/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ricksy.business;

public class RicksyBusiness {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new RicksyBusiness().getGreeting());
    }
}
