/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ricksy.business;

import org.junit.Test;
// import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        //RicksyBusiness classUnderTest = new RicksyBusiness();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
